"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$time\
$line_break$c\
$custom\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$character"""

palette = 'catppuccin_mocha'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#74512D'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
purple = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a3d1a1"
teal = "#94e2d5"
sky = "#89dceb"
dir = '#74614D'
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "fg:pink"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:text"
style_root = "fg:red"
format = '[ $user ]($style)'

[directory]
style = "fg:green"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"github" = "󰲋 "

[git_branch]
symbol = ""
style = ""
format = '[[$symbol $branch ](fg:sky)]($style)'

[git_status]
style = ""
format = '[[($all_status$ahead_behind )](fg:sky)]($style)'

[nodejs]
symbol = ""
style = ""
format = '[[$symbol ](fg:teal )]($style)'

[c]
symbol = ""
style = ""
format = '[[$symbol ](fg:sapphire )]($style)'

[custom.cpp]
detect_extensions = ['cpp', 'cc', 'hpp']
command = "echo ''"  
format = "[](fg:blue) "  
disabled = false

[rust]
symbol = ""
style = ""
format = '[[$symbol ](fg:peach )]($style)'

[golang]
symbol = ""
style = ""
format = '[[$symbol ](fg:red )]($style)'

[php]
symbol = ""
style = ""
format = '[[$symbol ](fg:subtext0 )]($style)'

[java]
symbol = ""
style = ""
format = '[[$symbol ](fg:red )]($style)'

[kotlin]
symbol = ""
style = ""
format = '[[$symbol ](fg:purple )]($style)'

[haskell]
symbol = ""
style = ""
format = '[[$symbol ](fg:rosewater )]($style)'

[python]
symbol = ""
style = ""
format = '[[$symbol ](fg:yellow )]($style)'

[docker_context]
symbol = ""
style = ""
format = '[[ $symbol( $context) ](fg:sky)]($style)'

[time]
disabled = true
time_format = "%R"
style = ""
format = '[[  $time ](fg:subtext1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[>](bold fg:green)'
error_symbol = '[>](bold fg:red)'
vimcmd_symbol = '[<](bold fg:creen)'
vimcmd_replace_one_symbol = '[<](bold fg:purple)'
vimcmd_replace_symbol = '[<](bold fg:purple)'
vimcmd_visual_symbol = '[<](bold fg:lavender)'
