github.com:
    users:
        andreamu02:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: andreamu02
